services:
  - type: web
    name: tru-backend
    env: node
    plan: free
    root: backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
